import { Skill } from "./types";

export const skills: Skill[] = [
  // ML/DL Skills
  {
    name: "Python",
    category: "languages",
    domain: "ml",
    logo: "skills/python.svg",
    proficiency: 95,
    projects: [
      "Computer Vision Pipeline",
      "Reinforcement Learning Models",
      "Stock Price Prediction",
    ],
  },
  {
    name: "PyTorch",
    category: "frameworks",
    domain: "ml",
    logo: "skills/pytorch.svg",
    proficiency: 80,
    projects: [
      "Drivable Area Segmentation",
      "Instance Segmentation Models",
      "RL Game AI Development",
    ],
  },
  {
    name: "C++",
    category: "languages",
    domain: "ml",
    logo: "skills/cpp.svg",
    proficiency: 75,
    projects: [
      "Real-time Segmentation",
      "CUDA GPU Acceleration",
      "Performance Optimization",
    ],
  },
  {
    name: "AWS",
    category: "tools",
    domain: "ml",
    logo: "skills/aws.svg",
    proficiency: 75,
    projects: [
      "Cloud ML Infrastructure",
      "Model Deployment Pipeline",
      "Scalable ML Solutions",
    ],
  },
  {
    name: "PostgreSQL",
    category: "databases",
    domain: "ml",
    logo: "skills/postgresql.svg",
    proficiency: 80,
    projects: [
      "Financial Data Analysis",
      "Time Series Forecasting",
      "Database Optimization",
    ],
  },

  // Software Engineering/Development Skills
  {
    name: "JavaScript",
    category: "languages",
    domain: "development",
    logo: "skills/javascript.svg",
    proficiency: 90,
    projects: [
      "Personal Portfolio",
      "Interactive Web Apps",
      "Dynamic User Interfaces",
    ],
  },
  {
    name: "TypeScript",
    category: "languages",
    domain: "development",
    logo: "skills/typescript.svg",
    proficiency: 85,
    projects: [
      "Type-Safe Web Apps",
      "Component Libraries",
      "Full-Stack Applications",
    ],
  },
  {
    name: "React",
    category: "frameworks",
    domain: "development",
    logo: "skills/react.svg",
    proficiency: 90,
    projects: ["Interactive Dashboards", "Modern Web Apps", "Responsive UIs"],
  },
  {
    name: "Next.js",
    category: "frameworks",
    domain: "development",
    logo: "skills/nextjs.svg",
    proficiency: 85,
    projects: ["Personal Portfolio", "Modern Web Apps", "SEO-Optimized Sites"],
  },
  {
    name: "Node.js",
    category: "frameworks",
    domain: "development",
    logo: "skills/nodejs.svg",
    proficiency: 80,
    projects: [
      "Backend Services",
      "API Development",
      "Server-Side Applications",
    ],
  },
  {
    name: "Git",
    category: "tools",
    domain: "development",
    logo: "skills/git.svg",
    proficiency: 90,
    projects: [
      "Project Version Control",
      "Collaborative Development",
      "Code Management",
    ],
  },
  {
    name: "Docker",
    category: "tools",
    domain: "development",
    logo: "skills/docker.svg",
    proficiency: 80,
    projects: [
      "Application Containerization",
      "Development Environments",
      "Deployment Solutions",
    ],
  },
  {
    name: "Kubernetes",
    category: "tools",
    domain: "development",
    logo: "skills/kubernetes.svg",
    proficiency: 70,
    projects: [
      "Container Management",
      "Scalable Deployments",
      "Infrastructure Automation",
    ],
  },
  {
    name: "Linux",
    category: "tools",
    domain: "development",
    logo: "skills/linux.svg",
    proficiency: 85,
    projects: [
      "System Administration",
      "Automation Scripts",
      "Performance Tuning",
    ],
  },
  {
    name: "Redis",
    category: "databases",
    domain: "development",
    logo: "skills/redis.svg",
    proficiency: 70,
    projects: ["Caching Solutions", "Session Storage", "Performance Optimization"],
  },
  {
    name: "NumPy",
    category: "frameworks",
    domain: "ml",
    logo: "skills/numpy.svg",
    proficiency: 85,
    projects: [
      "Data Analysis",
      "Mathematical Operations",
      "Array Processing",
    ],
  },
  {
    name: "OpenCV",
    category: "frameworks",
    domain: "ml",
    logo: "skills/opencv.svg",
    proficiency: 80,
    projects: [
      "Computer Vision",
      "Image Processing",
      "Real-time Analysis",
    ],
  },
  {
    name: "TensorFlow",
    category: "frameworks",
    domain: "ml",
    logo: "skills/tensorflow.svg",
    proficiency: 75,
    projects: [
      "Deep Learning Models",
      "Neural Networks",
      "Model Training",
    ],
  },
  {
    name: "Matplotlib",
    category: "tools",
    domain: "ml",
    logo: "skills/matplotlib.svg",
    proficiency: 80,
    projects: [
      "Data Visualization",
      "Chart Generation",
      "Statistical Plots",
    ],
  },
];
